// ================================================================================
// ================================================================================
// - File:    unit_test.c
// - Purpose: This file contains an implementation of the cmocka unit test frameword 
//            for the c_string library
//
// Source Metadata
// - Author:  Jonathan A. Webb
// - Date:    December 30, 2024
// - Version: 0.1
// - Copyright: Copyright 2024, Jon Webb Inc.
// ================================================================================
// ================================================================================
// Include modules here

#include <stdio.h>
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <stdint.h>
#include <cmocka.h>

#include "test_string.h"
#include "test_float.h"
#include "test_double.h"
#include "test_ldouble.h"
#include "test_int.h"
// ================================================================================ 
// ================================================================================
// Begin code

const struct CMUnitTest test_string[] = {
    cmocka_unit_test(test_init_string_nominal),
    cmocka_unit_test(test_init_string_empty),
    cmocka_unit_test(test_init_string_null),
    cmocka_unit_test(test_free_string_nominal),
    cmocka_unit_test(test_free_string_null),
    cmocka_unit_test(test_init_string_special_chars),
    cmocka_unit_test(test_init_string_long),
    cmocka_unit_test(test_getters_null),
    #if defined (__GNUC__) || defined (__clang__)
        cmocka_unit_test(test_string_cleanup_gbc),
    #endif
    cmocka_unit_test(test_concat_string_nominal),
    cmocka_unit_test(test_concat_literal_nominal),
    cmocka_unit_test(test_concat_empty_string),
    cmocka_unit_test(test_concat_empty_literal),
    cmocka_unit_test(test_concat_null_inputs),
    cmocka_unit_test(test_concat_reallocation),
    cmocka_unit_test(test_concat_multiple_times),
    cmocka_unit_test(test_concat_special_characters),
    cmocka_unit_test(test_concat_large_strings),
    cmocka_unit_test(test_compare_strings_equal),
    cmocka_unit_test(test_compare_strings_less),
    cmocka_unit_test(test_compare_strings_greater),
    cmocka_unit_test(test_compare_strings_different_lengths),
    cmocka_unit_test(test_compare_strings_empty),
    cmocka_unit_test(test_compare_strings_null),
    cmocka_unit_test(test_compare_strings_case_sensitivity), 
    cmocka_unit_test(test_copy_string_nominal),
    cmocka_unit_test(test_copy_string_empty),
    cmocka_unit_test(test_copy_string_null),
    cmocka_unit_test(test_reserve_string_nominal),
    cmocka_unit_test(test_reserve_string_smaller_size),
    cmocka_unit_test(test_reserve_string_null),
    cmocka_unit_test(test_trim_string_nominal),
    cmocka_unit_test(test_trim_already_minimal),
    cmocka_unit_test(test_trim_empty_string),
    cmocka_unit_test(test_first_char_occurance_nominal),
    cmocka_unit_test(test_first_char_occurance_not_found),
    cmocka_unit_test(test_first_char_occurance_empty_string),
    cmocka_unit_test(test_first_char_occurance_null),
    cmocka_unit_test(test_last_char_occurance_nominal),
    cmocka_unit_test(test_last_char_occurance_first_char),
    cmocka_unit_test(test_last_char_occurance_not_found),
    cmocka_unit_test(test_last_char_occurance_empty_string),
    cmocka_unit_test(test_last_char_occurance_null),
    cmocka_unit_test(test_string_start_pointer_nominal),
    cmocka_unit_test(test_string_start_pointer_empty),
    cmocka_unit_test(test_string_start_pointer_null),
    cmocka_unit_test(test_string_end_pointer_nominal),
    cmocka_unit_test(test_string_end_pointer_single_char),
    cmocka_unit_test(test_string_end_pointer_empty),
    cmocka_unit_test(test_string_end_pointer_null),
    cmocka_unit_test(test_pointer_arithmetic),
    cmocka_unit_test(test_first_substr_literal_nominal),
    cmocka_unit_test(test_first_substr_literal_middle),
    cmocka_unit_test(test_first_substr_literal_not_found),
    cmocka_unit_test(test_first_substr_literal_empty_substring),
    cmocka_unit_test(test_first_substr_literal_too_long),
    cmocka_unit_test(test_first_substr_string_nominal),
    cmocka_unit_test(test_first_substr_string_middle),
    cmocka_unit_test(test_first_substr_string_not_found),
    cmocka_unit_test(test_first_substr_string_empty),
    cmocka_unit_test(test_first_substr_string_too_long),
    cmocka_unit_test(test_last_substr_literal_nominal),
    cmocka_unit_test(test_last_substr_literal_single_occurrence),
    cmocka_unit_test(test_last_substr_literal_not_found),
    cmocka_unit_test(test_last_substr_literal_empty_substring),
    cmocka_unit_test(test_last_substr_literal_too_long),
    cmocka_unit_test(test_last_substr_string_single_occurrence),
    cmocka_unit_test(test_last_substr_string_not_found),
    cmocka_unit_test(test_last_substr_string_empty),
    cmocka_unit_test(test_last_substr_string_too_long),
    cmocka_unit_test(test_is_string_ptr_within_bounds),
    cmocka_unit_test(test_is_string_ptr_at_boundaries),
    cmocka_unit_test(test_is_string_ptr_outside_bounds),
    cmocka_unit_test(test_is_string_ptr_empty_string),
    cmocka_unit_test(test_is_string_ptr_null_inputs),
    cmocka_unit_test(test_drop_substring_literal_nominal),
    cmocka_unit_test(test_drop_substring_literal_with_spaces),
    cmocka_unit_test(test_drop_substring_literal_partial_range),
    cmocka_unit_test(test_drop_substring_string_nominal),
    cmocka_unit_test(test_drop_substring_string_with_spaces),
    cmocka_unit_test(test_drop_substring_not_found),
    cmocka_unit_test(test_drop_substring_invalid_range),
    cmocka_unit_test(test_replace_substr_literal_nominal),
    cmocka_unit_test(test_replace_substr_literal_shorter_replacement),
    cmocka_unit_test(test_replace_substr_literal_longer_replacement),
    cmocka_unit_test(test_replace_substr_literal_partial_range),
    cmocka_unit_test(test_replace_substr_string_nominal),
    cmocka_unit_test(test_replace_substr_string_shorter_replacement),
    cmocka_unit_test(test_replace_substr_string_longer_replacement),
    cmocka_unit_test(test_replace_substr_string_partial_range),
    cmocka_unit_test(test_replace_substr_invalid_range),
    cmocka_unit_test(test_lowercase_char_nominal),
    cmocka_unit_test(test_uppercase_char_nominal),
    cmocka_unit_test(test_lowercase_char_null_value),
    cmocka_unit_test(test_uppercase_char_nominal),
    cmocka_unit_test(test_uppercase_string_nominal),
    cmocka_unit_test(test_lowercase_string_nominal),
    cmocka_unit_test(test_uppercase_string_null),
    cmocka_unit_test(test_lowercase_string_null),
    cmocka_unit_test(test_pop_token_nominal),
    cmocka_unit_test(test_pop_token_multiple_tokens),
    cmocka_unit_test(test_pop_token_at_end),
    cmocka_unit_test(test_pop_token_no_token),
    cmocka_unit_test(test_pop_token_empty_string),
    cmocka_unit_test(test_pop_token_null_input),
    cmocka_unit_test(test_pop_token_single_char),
    cmocka_unit_test(test_pop_token_consecutive_tokens),
    cmocka_unit_test(test_token_count_single_delimiter),
    cmocka_unit_test(test_token_count_multiple_delimiters),
    cmocka_unit_test(test_token_count_consecutive_delimiters),
    cmocka_unit_test(test_token_count_leading_trailing_delimiters),
    cmocka_unit_test(test_token_count_single_token),
    cmocka_unit_test(test_token_count_empty_string),
    cmocka_unit_test(test_token_count_null_inputs),
    cmocka_unit_test(test_token_count_only_delimiters),
    cmocka_unit_test(test_token_count_mixed_delimiters),
    cmocka_unit_test(test_get_char_nominal),
    cmocka_unit_test(test_get_char_out_of_bounds),
    cmocka_unit_test(test_get_char_null),
    cmocka_unit_test(test_replace_char_nominal),
    cmocka_unit_test(test_replace_char_out_of_bounds),
    cmocka_unit_test(test_replace_char_null),
    cmocka_unit_test(test_replace_char_special_chars),
    cmocka_unit_test(test_trim_leading_nominal),
    cmocka_unit_test(test_trim_leading_multiple_types),
    cmocka_unit_test(test_trim_leading_no_whitespace),
    cmocka_unit_test(test_trim_trailing_nominal),
    cmocka_unit_test(test_trim_trailing_multiple_types),
    cmocka_unit_test(test_trim_trailing_no_whitespace),
    cmocka_unit_test(test_trim_all_nominal),
    cmocka_unit_test(test_trim_all_multiple_types),
    cmocka_unit_test(test_trim_all_no_whitespace),
    cmocka_unit_test(test_string_iterator_forward),
    cmocka_unit_test(test_string_iterator_reverse),
    cmocka_unit_test(test_string_iterator_empty_string),
    cmocka_unit_test(test_string_iterator_null_string),
    cmocka_unit_test(test_string_iterator_bounds),
    cmocka_unit_test(test_tokenize_basic),
    cmocka_unit_test(test_tokenize_multiple_delimiters),
    cmocka_unit_test(test_tokenize_consecutive_delimiters),
    cmocka_unit_test(test_tokenize_empty_string),
    cmocka_unit_test(test_tokenize_no_delimiters_found),
    cmocka_unit_test(test_tokenize_only_delimiters),
    cmocka_unit_test(test_tokenize_null_inputs),
    cmocka_unit_test(test_tokenize_empty_delimiter),
};
// --------------------------------------------------------------------------------

const struct CMUnitTest test_string_vector[] = {
	cmocka_unit_test(test_str_vector_init),
    cmocka_unit_test(test_str_vector_push_back),
    cmocka_unit_test(test_str_vector_auto_resize),
    cmocka_unit_test(test_str_vector_null_inputs),
    cmocka_unit_test(test_str_vector_empty_string),
    cmocka_unit_test(test_str_vector_multiple_pushes),
    #if defined (__GNUC__) || defined (__clang__) 
        cmocka_unit_test(test_str_vector_gbc),
    #endif
    cmocka_unit_test(test_push_front_empty_vector),
    cmocka_unit_test(test_push_front_existing_elements),
    cmocka_unit_test(test_push_front_reallocation),
    cmocka_unit_test(test_push_front_multiple),
    cmocka_unit_test(test_push_front_null_inputs),
    cmocka_unit_test(test_push_front_empty_string),
    cmocka_unit_test(test_insert_str_vector_middle),
    cmocka_unit_test(test_insert_str_vector_start),
    cmocka_unit_test(test_insert_str_vector_end),
    cmocka_unit_test(test_insert_str_vector_reallocation),
    cmocka_unit_test(test_insert_str_vector_invalid_index),
    cmocka_unit_test(test_insert_str_vector_null_inputs),
    cmocka_unit_test(test_insert_str_vector_empty_string),
    cmocka_unit_test(test_pop_back_nominal),
    cmocka_unit_test(test_pop_front_nominal),
    cmocka_unit_test(test_pop_empty_vector),
    cmocka_unit_test(test_pop_multiple_back),
    cmocka_unit_test(test_pop_multiple_front),
    cmocka_unit_test(test_pop_null_vector),
    cmocka_unit_test(test_pop_alternating),
    cmocka_unit_test(test_pop_any_nominal),
    cmocka_unit_test(test_pop_any_first),
    cmocka_unit_test(test_pop_any_last),
    cmocka_unit_test(test_pop_any_invalid_index),
    cmocka_unit_test(test_pop_any_empty_vector),
    cmocka_unit_test(test_pop_any_null_vector),
    cmocka_unit_test(test_pop_any_multiple),
    cmocka_unit_test(test_sort_empty_vector),
    cmocka_unit_test(test_sort_single_element),
    cmocka_unit_test(test_sort_forward_already_sorted),
    cmocka_unit_test(test_sort_forward_reverse_sorted),
    cmocka_unit_test(test_sort_reverse_already_sorted),
    cmocka_unit_test(test_sort_large_vector),
    cmocka_unit_test(test_sort_duplicate_elements),
    cmocka_unit_test(test_sort_with_empty_strings),
    cmocka_unit_test(test_sort_null_vector),
    cmocka_unit_test(test_delete_back_nominal),
    cmocka_unit_test(test_delete_front_nominal),
    cmocka_unit_test(test_delete_empty_vector),
    cmocka_unit_test(test_delete_multiple_back),
    cmocka_unit_test(test_delete_multiple_front),
    cmocka_unit_test(test_delete_null_vector),
    cmocka_unit_test(test_delete_alternating),
    cmocka_unit_test(test_delete_any_nominal),
    cmocka_unit_test(test_delete_any_first),
    cmocka_unit_test(test_delete_any_last),
    cmocka_unit_test(test_delete_any_invalid_index),
    cmocka_unit_test(test_delete_any_empty_vector),
    cmocka_unit_test(test_delete_null_vector),
    cmocka_unit_test(test_delete_any_multiple),
    cmocka_unit_test(test_reverse_str_vector),
};
// ================================================================================ 
// ================================================================================ 

const struct CMUnitTest test_float_vector[] = {
	cmocka_unit_test(test_init_float_vector_success),
    cmocka_unit_test(test_init_float_vector_zero_size),
    cmocka_unit_test(test_init_float_array_success),
    cmocka_unit_test(test_free_float_vector_null),
    cmocka_unit_test(test_free_float_vector_static),
    #if defined(__GNUC__) || defined(__clang__)
        cmocka_unit_test(test_float_vector_gbc),
    #endif
    cmocka_unit_test(test_push_back_basic),
    cmocka_unit_test(test_push_back_growth),
    cmocka_unit_test(test_push_back_static),
    cmocka_unit_test(test_generic_macros),
    cmocka_unit_test(test_float_vector_index),
    cmocka_unit_test(test_push_back_special_values),
    cmocka_unit_test(test_static_array_bounds),
    cmocka_unit_test(test_static_array_index_bounds),
    cmocka_unit_test(test_static_array_initialization),
    cmocka_unit_test(test_static_array_free),
    cmocka_unit_test(test_push_front_basic),
    cmocka_unit_test(test_push_front_growth),
    cmocka_unit_test(test_push_front_static),
    cmocka_unit_test(test_push_front_special_values),
    cmocka_unit_test(test_push_front_error_cases),
    cmocka_unit_test(test_insert_vector_basic),
    cmocka_unit_test(test_insert_vector_growth),
    cmocka_unit_test(test_insert_array_basic),
    cmocka_unit_test(test_insert_array_bounds),
    cmocka_unit_test(test_insert_error_cases),
    cmocka_unit_test(test_insert_special_values),
    cmocka_unit_test(test_pop_back_basic),
    cmocka_unit_test(test_pop_back_empty),
    cmocka_unit_test(test_pop_back_errors),
    cmocka_unit_test(test_pop_back_special_values),
    cmocka_unit_test(test_pop_back_static),
    cmocka_unit_test(test_pop_front_basic),
    cmocka_unit_test(test_pop_front_empty),
    cmocka_unit_test(test_pop_front_errors),
    cmocka_unit_test(test_pop_front_special_values),
    cmocka_unit_test(test_pop_front_static),
    cmocka_unit_test(test_pop_any_basic),
    cmocka_unit_test(test_pop_any_errors),
    cmocka_unit_test(test_pop_any_static),
    cmocka_unit_test(test_pop_any_special_values),
    cmocka_unit_test(test_reverse_basic),
    cmocka_unit_test(test_reverse_errors),
    cmocka_unit_test(test_reverse_static),
    cmocka_unit_test(test_reverse_special_values),
    cmocka_unit_test(test_sort_basic),
    cmocka_unit_test(test_sort_edge_cases),
    cmocka_unit_test(test_sort_duplicates),
    cmocka_unit_test(test_sort_special_values),
    cmocka_unit_test(test_sort_static_array),
    cmocka_unit_test(test_sort_errors),
    cmocka_unit_test(test_trim_basic),
    cmocka_unit_test(test_trim_empty_vector),
    cmocka_unit_test(test_trim_static_array),
    cmocka_unit_test(test_trim_already_optimal),
    cmocka_unit_test(test_trim_errors),
    cmocka_unit_test(test_binary_search_basic),
    cmocka_unit_test(test_binary_search_tolerance),
    cmocka_unit_test(test_binary_search_with_sort),
    cmocka_unit_test(test_binary_search_errors),
    cmocka_unit_test(test_binary_search_static),
    cmocka_unit_test(test_update_float_vector_nominal),
    cmocka_unit_test(test_update_float_vector_bad_index),
    cmocka_unit_test(test_update_float_vector_null),
    cmocka_unit_test(test_min_float_basic),
    cmocka_unit_test(test_max_float_basic),
    cmocka_unit_test(test_min_max_special_values),
    cmocka_unit_test(test_min_max_static_array),
    cmocka_unit_test(test_min_max_errors),
    cmocka_unit_test(test_sum_basic),
    cmocka_unit_test(test_average_basic),
    cmocka_unit_test(test_sum_average_special_values),
    cmocka_unit_test(test_sum_average_negative),
    cmocka_unit_test(test_sum_average_static),
    cmocka_unit_test(test_sum_average_errors),
    cmocka_unit_test(test_stdev_basic),
    cmocka_unit_test(test_stdev_single_value),
    cmocka_unit_test(test_stdev_same_values),
    cmocka_unit_test(test_cum_sum_basic),
    cmocka_unit_test(test_cum_sum_negative),
    cmocka_unit_test(test_stdev_cum_sum_special_values),
    cmocka_unit_test(test_stdev_cum_sum_errors),
    cmocka_unit_test(test_dot_product_basic),
    cmocka_unit_test(test_dot_product_mismatched_lengths),
    cmocka_unit_test(test_dot_product_null_inputs),
    cmocka_unit_test(test_dot_product_zero_length),
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_float_dict[] = {
    cmocka_unit_test(test_init_float_dict),
    #if defined (__GNUC__) || defined (__clang__)
        cmocka_unit_test(test_dictionary_float_gbc),
    #endif
    cmocka_unit_test_setup_teardown(test_insert_float_dict_basic, setup, teardown),
    cmocka_unit_test_setup_teardown(test_insert_float_dict_duplicate, setup, teardown),
    cmocka_unit_test_setup_teardown(test_insert_float_dict_null, setup, teardown),
    cmocka_unit_test_setup_teardown(test_get_float_dict_value_basic, setup, teardown),
    cmocka_unit_test_setup_teardown(test_get_float_dict_value_missing, setup, teardown),
    cmocka_unit_test_setup_teardown(test_update_float_dict_basic, setup, teardown),
    cmocka_unit_test_setup_teardown(test_update_float_dict_missing, setup, teardown),
    cmocka_unit_test_setup_teardown(test_pop_float_dict_basic, setup, teardown),
    cmocka_unit_test_setup_teardown(test_pop_float_dict_missing, setup, teardown),
    cmocka_unit_test_setup_teardown(test_resize_behavior, setup, teardown),
    cmocka_unit_test_setup_teardown(test_get_keys_float_dict, setup, teardown),
    cmocka_unit_test_setup_teardown(test_get_values_float_dict, setup, teardown),
    cmocka_unit_test_setup_teardown(test_foreach_float_dict_basic, setup, teardown),
    cmocka_unit_test_setup_teardown(test_foreach_float_dict_empty, setup, teardown),
    cmocka_unit_test_setup_teardown(test_foreach_float_dict_null, setup, teardown),
    cmocka_unit_test(test_vector_dictionary),
    cmocka_unit_test(test_vector_dictionary_resize),
    cmocka_unit_test(test_vector_dictionary_gbc),
    cmocka_unit_test(test_pop_vector_dictionary),
    cmocka_unit_test(test_insert_floatv_dict_basic),
    cmocka_unit_test(test_floatv_size_macros),
    cmocka_unit_test(test_copy_floatv_dict_success),
    cmocka_unit_test(test_copy_floatv_dict_null_input),
    cmocka_unit_test(test_copy_floatv_dict_static_vector),
    cmocka_unit_test(test_copy_floatv_dict_multiple_entries),
    cmocka_unit_test(test_copy_floatv_dict_independence),
    cmocka_unit_test(test_merge_floatv_dict_unique_keys),
    cmocka_unit_test(test_merge_floatv_dict_no_overwrite),
    cmocka_unit_test(test_merge_floatv_dict_overwrite),
    cmocka_unit_test(test_merge_floatv_dict_reject_static),
    cmocka_unit_test(test_merge_floatv_dict_null_inputs),
    cmocka_unit_test(test_clear_floatv_dict_basic),
    cmocka_unit_test(test_clear_floatv_dict_empty),
    cmocka_unit_test(test_clear_floatv_dict_reuse_after_clear),
    cmocka_unit_test(test_foreach_floatv_dict_counts_keys),
    cmocka_unit_test(test_foreach_floatv_dict_with_null_dict),
    cmocka_unit_test(test_foreach_floatv_dict_with_null_callback),
    cmocka_unit_test(test_foreach_floatv_dict_accumulates_sum),
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_float_matrix[] = {
    cmocka_unit_test(test_create_dense_float_matrix),
    cmocka_unit_test(test_insert_and_get_dense_float_matrix),
    cmocka_unit_test(test_invalid_dense_float_insert),
    cmocka_unit_test(test_float_coo_conversion_from_dense),
    cmocka_unit_test(test_insert_float_and_get_coo_matrix),
    cmocka_unit_test(test_duplicate_flaot_insert_coo_disallowed),
    cmocka_unit_test(test_float_csr_conversion_from_coo),
    cmocka_unit_test(test_get_after_float_csr_conversion),
    cmocka_unit_test(test_pop_after_float_csr_conversion),
    cmocka_unit_test(test_get_float_matrix_bounds),
    cmocka_unit_test(test_insert_float_matrix_bounds),
    cmocka_unit_test(test_pop_float_matrix_bounds),
    cmocka_unit_test(test_get_float_matrix_null),
    cmocka_unit_test(test_insert_float_matrix_null),
    cmocka_unit_test(test_pop_float_matrix_null),
    #if defined(__GNUC__) || defined(__clang__)
        cmocka_unit_test(test_float_matrix_gbc),
    #endif
    cmocka_unit_test(test_identity_inverse),
    cmocka_unit_test(test_known_inverse),
    cmocka_unit_test(test_singular_matrix),
    cmocka_unit_test(test_null_input),
    cmocka_unit_test(test_non_square_matrix),
    cmocka_unit_test(test_transpose_dense_identity),
    cmocka_unit_test(test_transpose_dense_general),
    cmocka_unit_test(test_transpose_dense_rectangular),
    cmocka_unit_test(test_transpose_coo_identity),
    cmocka_unit_test(test_transpose_coo_rectangular),
    cmocka_unit_test(test_transpose_csr_identity),
    cmocka_unit_test(test_transpose_csr_rectangular),
    cmocka_unit_test(test_copy_dense_matrix),
    cmocka_unit_test(test_copy_coo_matrix),
    cmocka_unit_test(test_copy_csr_matrix),
    cmocka_unit_test(test_det_identity_3x3),
    cmocka_unit_test(test_det_singular_2x2),
    cmocka_unit_test(test_det_known_2x2),
    cmocka_unit_test(test_det_known_3x3),
};
// ================================================================================ 
// ================================================================================ 

const struct CMUnitTest test_double_vector[] = {
	cmocka_unit_test(test_init_double_vector_success),
    cmocka_unit_test(test_init_double_vector_zero_size),
    cmocka_unit_test(test_init_double_array_success),
    cmocka_unit_test(test_free_double_vector_null),
    cmocka_unit_test(test_free_double_vector_static),
    #if defined(__GNUC__) || defined(__clang__)
        cmocka_unit_test(test_double_vector_gbc),
    #endif
    cmocka_unit_test(test_push_back_basic),
    cmocka_unit_test(test_push_back_growth),
    cmocka_unit_test(test_push_back_static),
    cmocka_unit_test(test_generic_macros),
    cmocka_unit_test(test_double_vector_index),
    cmocka_unit_test(test_push_back_special_values),
    cmocka_unit_test(test_static_array_bounds),
    cmocka_unit_test(test_static_array_index_bounds),
    cmocka_unit_test(test_static_array_initialization),
    cmocka_unit_test(test_static_array_free),
    cmocka_unit_test(test_push_front_basic),
    cmocka_unit_test(test_push_front_growth),
    cmocka_unit_test(test_push_front_static),
    cmocka_unit_test(test_push_front_special_values),
    cmocka_unit_test(test_push_front_error_cases),
    cmocka_unit_test(test_insert_vector_basic),
    cmocka_unit_test(test_insert_vector_growth),
    cmocka_unit_test(test_insert_array_basic),
    cmocka_unit_test(test_insert_array_bounds),
    cmocka_unit_test(test_insert_error_cases),
    cmocka_unit_test(test_insert_special_values),
    cmocka_unit_test(test_pop_back_basic),
    cmocka_unit_test(test_pop_back_empty),
    cmocka_unit_test(test_pop_back_errors),
    cmocka_unit_test(test_pop_back_special_values),
    cmocka_unit_test(test_pop_back_static),
    cmocka_unit_test(test_pop_front_basic),
    cmocka_unit_test(test_pop_front_empty),
    cmocka_unit_test(test_pop_front_errors),
    cmocka_unit_test(test_pop_front_special_values),
    cmocka_unit_test(test_pop_front_static),
    cmocka_unit_test(test_pop_any_basic),
    cmocka_unit_test(test_pop_any_errors),
    cmocka_unit_test(test_pop_any_static),
    cmocka_unit_test(test_pop_any_special_values),
    cmocka_unit_test(test_reverse_basic),
    cmocka_unit_test(test_reverse_errors),
    cmocka_unit_test(test_reverse_static),
    cmocka_unit_test(test_reverse_special_values),
    cmocka_unit_test(test_sort_basic),
    cmocka_unit_test(test_sort_edge_cases),
    cmocka_unit_test(test_sort_duplicates),
    cmocka_unit_test(test_sort_special_values),
    cmocka_unit_test(test_sort_static_array),
    cmocka_unit_test(test_sort_errors),
    cmocka_unit_test(test_trim_basic),
    cmocka_unit_test(test_trim_empty_vector),
    cmocka_unit_test(test_trim_static_array),
    cmocka_unit_test(test_trim_already_optimal),
    cmocka_unit_test(test_trim_errors),
    cmocka_unit_test(test_binary_search_basic),
    cmocka_unit_test(test_binary_search_tolerance),
    cmocka_unit_test(test_binary_search_with_sort),
    cmocka_unit_test(test_binary_search_errors),
    cmocka_unit_test(test_binary_search_static),
    cmocka_unit_test(test_update_double_vector_nominal),
    cmocka_unit_test(test_update_double_vector_bad_index),
    cmocka_unit_test(test_update_double_vector_null),
    cmocka_unit_test(test_min_double_basic),
    cmocka_unit_test(test_max_double_basic),
    cmocka_unit_test(test_min_max_special_values),
    cmocka_unit_test(test_min_max_static_array),
    cmocka_unit_test(test_min_max_errors),
    cmocka_unit_test(test_sum_basic),
    cmocka_unit_test(test_average_basic),
    cmocka_unit_test(test_sum_average_special_values),
    cmocka_unit_test(test_sum_average_negative),
    cmocka_unit_test(test_sum_average_static),
    cmocka_unit_test(test_sum_average_errors),
    cmocka_unit_test(test_stdev_basic),
    cmocka_unit_test(test_stdev_single_value),
    cmocka_unit_test(test_stdev_same_values),
    cmocka_unit_test(test_cum_sum_basic),
    cmocka_unit_test(test_cum_sum_negative),
    cmocka_unit_test(test_stdev_cum_sum_special_values),
    cmocka_unit_test(test_stdev_cum_sum_errors),
    cmocka_unit_test(test_dot_double_product_basic),
    cmocka_unit_test(test_dot_double_product_mismatched_lengths),
    cmocka_unit_test(test_dot_double_product_null_inputs),
    cmocka_unit_test(test_dot_double_product_zero_length),
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_double_dict[] = {
    cmocka_unit_test(test_dictionary_double_gbc),
    cmocka_unit_test_setup_teardown(test_insert_double_dict_basic, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_insert_double_dict_duplicate, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_insert_double_dict_null, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_get_double_dict_value_basic, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_get_double_dict_value_missing, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_update_double_dict_basic, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_update_double_dict_missing, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_pop_double_dict_basic, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_pop_double_dict_missing, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_resize_behavior, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_get_keys_double_dict, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_get_values_double_dict, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_foreach_double_dict_basic, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_foreach_double_dict_empty, setup_double, teardown_double),
    cmocka_unit_test_setup_teardown(test_foreach_double_dict_null, setup_double, teardown_double),
    cmocka_unit_test(test_vector_dictionary),
    cmocka_unit_test(test_vector_dictionary_resize),
    cmocka_unit_test(test_vector_dictionary_gbc),
    cmocka_unit_test(test_pop_vector_dictionary),
    cmocka_unit_test(test_insert_doublev_dict_basic),
    cmocka_unit_test(test_doublev_size_macros),
    cmocka_unit_test(test_copy_doublev_dict_success),
    cmocka_unit_test(test_copy_doublev_dict_null_input),
    cmocka_unit_test(test_copy_doublev_dict_static_vector),
    cmocka_unit_test(test_copy_doublev_dict_multiple_entries),
    cmocka_unit_test(test_copy_doublev_dict_independence),
    cmocka_unit_test(test_merge_doublev_dict_unique_keys),
    cmocka_unit_test(test_merge_doublev_dict_no_overwrite),
    cmocka_unit_test(test_merge_doublev_dict_overwrite),
    cmocka_unit_test(test_merge_doublev_dict_reject_static),
    cmocka_unit_test(test_merge_doublev_dict_null_inputs),
    cmocka_unit_test(test_clear_doublev_dict_basic),
    cmocka_unit_test(test_clear_doublev_dict_empty),
    cmocka_unit_test(test_clear_doublev_dict_reuse_after_clear),
    cmocka_unit_test(test_foreach_doublev_dict_counts_keys),
    cmocka_unit_test(test_foreach_doublev_dict_with_null_dict),
    cmocka_unit_test(test_foreach_doublev_dict_with_null_callback),
    cmocka_unit_test(test_foreach_doublev_dict_accumulates_sum),
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_ldouble_vector[] = {
	cmocka_unit_test(test_init_ldouble_vector_success),
    cmocka_unit_test(test_init_ldouble_vector_zero_size),
    cmocka_unit_test(test_init_ldouble_array_success),
    cmocka_unit_test(test_free_ldouble_vector_null),
    cmocka_unit_test(test_free_ldouble_vector_static),
    #if defined(__GNUC__) || defined(__clang__)
        cmocka_unit_test(test_ldouble_vector_gbc),
    #endif
    cmocka_unit_test(test_push_back_ldouble_basic),
    cmocka_unit_test(test_push_back_ldouble_growth),
    cmocka_unit_test(test_push_back_ldouble_static),
    cmocka_unit_test(test_generic_ldouble_macros),
    cmocka_unit_test(test_vector_ldouble_index),
    cmocka_unit_test(test_push_back_special_ldouble_values),
    cmocka_unit_test(test_static_array_ldouble_bounds),
    cmocka_unit_test(test_static_array_index_ldouble_bounds),
    cmocka_unit_test(test_static_array_ldouble_initialization),
    cmocka_unit_test(test_static_array_ldouble_free),
    cmocka_unit_test(test_push_front_ldouble_basic),
    cmocka_unit_test(test_push_front_ldouble_growth),
    cmocka_unit_test(test_push_front_ldouble_static),
    cmocka_unit_test(test_push_front_special_ldouble_values),
    cmocka_unit_test(test_push_front_error_ldouble_cases),
    cmocka_unit_test(test_insert_vector_ldouble_basic),
    cmocka_unit_test(test_insert_vector_ldouble_growth),
    cmocka_unit_test(test_insert_array_ldouble_basic),
    cmocka_unit_test(test_insert_array_ldouble_bounds),
    cmocka_unit_test(test_insert_error_ldouble_cases),
    cmocka_unit_test(test_insert_special_ldouble_values),
    cmocka_unit_test(test_pop_back_ldouble_basic),
    cmocka_unit_test(test_pop_back_ldouble_empty),
    cmocka_unit_test(test_pop_back_ldouble_errors),
    cmocka_unit_test(test_pop_back_special_ldouble_values),
    cmocka_unit_test(test_pop_back_ldouble_static),
    cmocka_unit_test(test_pop_front_ldouble_basic),
    cmocka_unit_test(test_pop_front_ldouble_empty),
    cmocka_unit_test(test_pop_front_ldouble_errors),
    cmocka_unit_test(test_pop_front_special_ldouble_values),
    cmocka_unit_test(test_pop_front_ldouble_static),
    cmocka_unit_test(test_pop_any_ldouble_basic),
    cmocka_unit_test(test_pop_any_ldouble_errors),
    cmocka_unit_test(test_pop_any_ldouble_static),
    cmocka_unit_test(test_pop_any_special_ldouble_values),
    cmocka_unit_test(test_reverse_ldouble_basic),
    cmocka_unit_test(test_reverse_ldouble_errors),
    cmocka_unit_test(test_reverse_ldouble_static),
    cmocka_unit_test(test_reverse_special_ldouble_values),
    cmocka_unit_test(test_sort_ldouble_basic),
    cmocka_unit_test(test_sort_edge_ldouble_cases),
    cmocka_unit_test(test_sort_ldouble_duplicates),
    cmocka_unit_test(test_sort_special_ldouble_values),
    cmocka_unit_test(test_sort_static_ldouble_array),
    cmocka_unit_test(test_sort_ldouble_errors),
    cmocka_unit_test(test_trim_ldouble_basic),
    cmocka_unit_test(test_trim_empty_ldouble_vector),
    cmocka_unit_test(test_trim_static_ldouble_array),
    cmocka_unit_test(test_trim_already_ldouble_optimal),
    cmocka_unit_test(test_trim_ldouble_errors),
    cmocka_unit_test(test_binary_search_ldouble_basic),
    cmocka_unit_test(test_binary_search_ldouble_tolerance),
    cmocka_unit_test(test_binary_search_with_ldouble_sort),
    cmocka_unit_test(test_binary_search_ldouble_errors),
    cmocka_unit_test(test_binary_search_ldouble_static),
    cmocka_unit_test(test_update_ldouble_vector_nominal),
    cmocka_unit_test(test_update_ldouble_vector_bad_index),
    cmocka_unit_test(test_update_ldouble_vector_null),
    cmocka_unit_test(test_min_ldouble_basic),
    cmocka_unit_test(test_max_ldouble_basic),
    cmocka_unit_test(test_min_max_special_ldouble_values),
    cmocka_unit_test(test_min_max_static_ldouble_array),
    cmocka_unit_test(test_min_max_ldouble_errors),
    cmocka_unit_test(test_sum_ldouble_basic),
    cmocka_unit_test(test_average_ldouble_basic),
    cmocka_unit_test(test_sum_average_special_ldouble_values),
    cmocka_unit_test(test_sum_average_ldouble_negative),
    cmocka_unit_test(test_sum_average_ldouble_static),
    cmocka_unit_test(test_stdev_ldouble_basic),
    cmocka_unit_test(test_stdev_single_ldouble_value),
    cmocka_unit_test(test_stdev_same_ldouble_values),
    cmocka_unit_test(test_cum_sum_ldouble_basic),
    cmocka_unit_test(test_cum_sum_ldouble_negative),
    cmocka_unit_test(test_stdev_cum_sum_ldouble_errors)
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_ldouble_dict[] = {
    cmocka_unit_test_setup_teardown(test_insert_ldouble_dict_basic, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_insert_ldouble_dict_duplicate, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_insert_ldouble_dict_null, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_get_ldouble_dict_value_basic, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_get_ldouble_dict_value_missing, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_update_ldouble_dict_basic, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_update_ldouble_dict_missing, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_pop_ldouble_dict_basic, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_pop_ldouble_dict_missing, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_get_keys_ldouble_dict, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_get_values_ldouble_dict, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_foreach_ldouble_dict_basic, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_foreach_ldouble_dict_empty, setup_ldouble, teardown_ldouble),
    cmocka_unit_test_setup_teardown(test_foreach_ldouble_dict_null, setup_ldouble, teardown_ldouble),
    cmocka_unit_test(test_vector_ldouble_dictionary),
    cmocka_unit_test(test_vector_dictionary_ldouble_resize),
    cmocka_unit_test(test_vector_dictionary_ldouble_gbc),
    cmocka_unit_test(test_pop_vector_ldouble_dictionary),
    cmocka_unit_test(test_insert_ldoublev_dict_basic),
    cmocka_unit_test(test_ldoublev_size_macros),
    cmocka_unit_test(test_copy_ldoublev_dict_success),
    cmocka_unit_test(test_copy_ldoublev_dict_null_input),
    cmocka_unit_test(test_copy_ldoublev_dict_static_vector),
    cmocka_unit_test(test_copy_ldoublev_dict_multiple_entries),
    cmocka_unit_test(test_copy_ldoublev_dict_independence),
    cmocka_unit_test(test_merge_ldoublev_dict_unique_keys),
    cmocka_unit_test(test_merge_ldoublev_dict_no_overwrite),
    cmocka_unit_test(test_merge_ldoublev_dict_overwrite),
    cmocka_unit_test(test_merge_ldoublev_dict_reject_static),
    cmocka_unit_test(test_merge_ldoublev_dict_null_inputs),
    cmocka_unit_test(test_clear_ldoublev_dict_basic),
    cmocka_unit_test(test_clear_ldoublev_dict_empty),
    cmocka_unit_test(test_clear_ldoublev_dict_reuse_after_clear),
    cmocka_unit_test(test_foreach_ldoublev_dict_counts_keys),
    cmocka_unit_test(test_foreach_ldoublev_dict_with_null_dict),
    cmocka_unit_test(test_foreach_ldoublev_dict_with_null_callback),
    cmocka_unit_test(test_foreach_ldoublev_dict_accumulates_sum),
};
// ================================================================================ 
// ================================================================================ 

const struct CMUnitTest test_int_vector[] = {
	cmocka_unit_test(test_init_int_vector_success),
    cmocka_unit_test(test_init_int_vector_zero_size),
    cmocka_unit_test(test_init_int_array_success),
    cmocka_unit_test(test_free_int_vector_null),
    cmocka_unit_test(test_free_int_vector_static),
    #if defined(__GNUC__) || defined(__clang__)
        cmocka_unit_test(test_int_vector_gbc),
    #endif
    cmocka_unit_test(test_push_back_int_basic),
    cmocka_unit_test(test_push_back_int_growth),
    cmocka_unit_test(test_push_back_int_static),
    cmocka_unit_test(test_generic_int_macros),
    cmocka_unit_test(test_int_vector_index),
    cmocka_unit_test(test_int_static_array_bounds),
    cmocka_unit_test(test_int_static_array_index_bounds),
    cmocka_unit_test(test_int_static_array_initialization),
    cmocka_unit_test(test_int_static_array_free),
    cmocka_unit_test(test_push_int_front_basic),
    cmocka_unit_test(test_push_int_front_growth),
    cmocka_unit_test(test_push_int_front_static),
    cmocka_unit_test(test_push_int_front_error_cases),
    cmocka_unit_test(test_insert_int_vector_basic),
    cmocka_unit_test(test_insert_int_vector_growth),
    cmocka_unit_test(test_insert_int_array_basic),
    cmocka_unit_test(test_insert_int_array_bounds),
    cmocka_unit_test(test_insert_int_error_cases),
    cmocka_unit_test(test_pop_back_int_basic),
    cmocka_unit_test(test_pop_back_int_empty),
    cmocka_unit_test(test_pop_back_int_errors),
    cmocka_unit_test(test_pop_back_int_static),
    cmocka_unit_test(test_pop_front_int_basic),
    cmocka_unit_test(test_pop_front_int_empty),
    cmocka_unit_test(test_pop_front_int_errors),
    cmocka_unit_test(test_pop_front_int_static),
    cmocka_unit_test(test_pop_any_int_basic),
    cmocka_unit_test(test_pop_any_int_errors),
    cmocka_unit_test(test_pop_any_int_static),
    cmocka_unit_test(test_reverse_int_basic),
    cmocka_unit_test(test_reverse_int_errors),
    cmocka_unit_test(test_reverse_int_static),
    cmocka_unit_test(test_sort_int_basic),
    cmocka_unit_test(test_sort_int_edge_cases),
    cmocka_unit_test(test_sort_int_duplicates),
    cmocka_unit_test(test_sort_static_int_array),
    cmocka_unit_test(test_sort_int_errors),
    cmocka_unit_test(test_trim_int_basic),
    cmocka_unit_test(test_trim_empty_int_vector),
    cmocka_unit_test(test_trim_static_int_array),
    cmocka_unit_test(test_trim_already_int_optimal),
    cmocka_unit_test(test_trim_int_errors),
    cmocka_unit_test(test_binary_search_int_basic),
    cmocka_unit_test(test_binary_search_int_with_sort),
    cmocka_unit_test(test_binary_search_int_errors),
    cmocka_unit_test(test_binary_search_int_static),
    cmocka_unit_test(test_update_int_vector_nominal),
    cmocka_unit_test(test_update_int_vector_bad_index),
    cmocka_unit_test(test_update_int_vector_null),
    cmocka_unit_test(test_min_int_basic),
    cmocka_unit_test(test_max_int_basic),
    cmocka_unit_test(test_min_max_static_int_array),
    cmocka_unit_test(test_min_max_int_errors),
    cmocka_unit_test(test_sum_int_basic),
    cmocka_unit_test(test_average_int_basic),
    cmocka_unit_test(test_sum_average_int_negative),
    cmocka_unit_test(test_sum_average_int_static),
    cmocka_unit_test(test_stdev_int_basic),
    cmocka_unit_test(test_stdev_single_int_value),
    cmocka_unit_test(test_stdev_same_int_values),
    cmocka_unit_test(test_cum_sum_int_basic),
    cmocka_unit_test(test_stdev_cum_sum_int_errors)
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_int_dict[] = {
    cmocka_unit_test(test_init_int_dict),
    #if defined (__GNUC__) || defined (__clang__)
        cmocka_unit_test(test_dictionary_int_gbc),
    #endif
    cmocka_unit_test_setup_teardown(test_insert_int_dict_basic, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_insert_int_dict_duplicate, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_insert_int_dict_null, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_get_int_dict_value_basic, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_get_int_dict_value_missing, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_update_int_dict_basic, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_update_int_dict_missing, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_pop_int_dict_basic, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_pop_int_dict_missing, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_resize_int_behavior, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_get_keys_int_dict, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_get_values_int_dict, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_foreach_int_dict_basic, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_foreach_int_dict_empty, setup_int, teardown_int),
    cmocka_unit_test_setup_teardown(test_foreach_int_dict_null, setup_int, teardown_int),
    cmocka_unit_test(test_int_vector_dictionary),
    cmocka_unit_test(test_int_vector_dictionary_resize),
    cmocka_unit_test(test_int_vector_dictionary_gbc),
    cmocka_unit_test(test_pop_int_vector_dictionary),
    cmocka_unit_test(test_insert_intv_dict_basic),
    cmocka_unit_test(test_intv_size_macros),
    cmocka_unit_test(test_copy_intv_dict_success),
    cmocka_unit_test(test_copy_intv_dict_null_input),
    cmocka_unit_test(test_copy_intv_dict_static_vector),
    cmocka_unit_test(test_copy_intv_dict_multiple_entries),
    cmocka_unit_test(test_copy_intv_dict_independence),
    cmocka_unit_test(test_merge_intv_dict_unique_keys),
    cmocka_unit_test(test_merge_intv_dict_no_overwrite),
    cmocka_unit_test(test_merge_intv_dict_overwrite),
    cmocka_unit_test(test_merge_intv_dict_reject_static),
    cmocka_unit_test(test_merge_intv_dict_null_inputs),
    cmocka_unit_test(test_clear_intv_dict_basic),
    cmocka_unit_test(test_clear_intv_dict_empty),
    cmocka_unit_test(test_clear_intv_dict_reuse_after_clear),
    cmocka_unit_test(test_foreach_intv_dict_counts_keys),
    cmocka_unit_test(test_foreach_intv_dict_with_null_dict),
    cmocka_unit_test(test_foreach_intv_dict_with_null_callback),
    cmocka_unit_test(test_foreach_intv_dict_accumulates_sum),
};
// -------------------------------------------------------------------------------- 

const struct CMUnitTest test_double_matrix[] = {
    cmocka_unit_test(test_create_dense_double_matrix),
    cmocka_unit_test(test_insert_and_get_dense_double_matrix),
    cmocka_unit_test(test_invalid_dense_double_insert),
    cmocka_unit_test(test_double_coo_conversion_from_dense),
    cmocka_unit_test(test_insert_double_and_get_coo_matrix),
    cmocka_unit_test(test_duplicate_flaot_insert_coo_disallowed),
    cmocka_unit_test(test_double_csr_conversion_from_coo),
    cmocka_unit_test(test_get_after_double_csr_conversion),
    cmocka_unit_test(test_pop_after_double_csr_conversion),
    cmocka_unit_test(test_get_double_matrix_bounds),
    cmocka_unit_test(test_insert_double_matrix_bounds),
    cmocka_unit_test(test_pop_double_matrix_bounds),
    cmocka_unit_test(test_get_double_matrix_null),
    cmocka_unit_test(test_insert_double_matrix_null),
    cmocka_unit_test(test_pop_double_matrix_null),
    #if defined(__GNUC__) || defined(__clang__)
        cmocka_unit_test(test_double_matrix_gbc),
    #endif
    cmocka_unit_test(test_double_identity_inverse),
    cmocka_unit_test(test_double_known_inverse),
    cmocka_unit_test(test_double_singular_matrix),
    cmocka_unit_test(test_double_null_input),
    cmocka_unit_test(test_double_non_square_matrix),
    cmocka_unit_test(test_double_transpose_dense_identity),
    cmocka_unit_test(test_double_transpose_dense_general),
    cmocka_unit_test(test_double_transpose_dense_rectangular),
    cmocka_unit_test(test_double_transpose_coo_identity),
    cmocka_unit_test(test_double_transpose_coo_rectangular),
    cmocka_unit_test(test_double_transpose_csr_identity),
    cmocka_unit_test(test_double_transpose_csr_rectangular),
    cmocka_unit_test(test_copy_double_dense_matrix),
    cmocka_unit_test(test_copy_double_coo_matrix),
    cmocka_unit_test(test_copy_double_csr_matrix),
    cmocka_unit_test(test_det_double_identity_3x3),
    cmocka_unit_test(test_det_double_singular_2x2),
    cmocka_unit_test(test_det_double_known_2x2),
    cmocka_unit_test(test_det_double_known_3x3),
};
// ================================================================================ 
// ================================================================================ 
int main(int argc, const char * argv[]) {
    int status;
    status = cmocka_run_group_tests(test_string, NULL, NULL);
    if (status != 0) 
        return status;	
    status = cmocka_run_group_tests(test_string_vector, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_float_vector, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_float_dict, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_float_matrix, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_double_vector, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_double_dict, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_ldouble_vector, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_ldouble_dict, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_int_vector, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_int_dict, NULL, NULL);
    if (status != 0) 
        return status;
    status = cmocka_run_group_tests(test_double_matrix, NULL, NULL);
	return status;
}
// ================================================================================
// ================================================================================
// eof

